//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_people
    {
        public tbl_people()
        {
            this.tbl_duty = new HashSet<tbl_duty>();
            this.tbl_menu_selection = new HashSet<tbl_menu_selection>();
        }
    
        public long id { get; set; }
        public string people_name { get; set; }
        public Nullable<bool> takes_meal { get; set; }
        public Nullable<bool> excepts_duty { get; set; }
        public Nullable<long> id_group { get; set; }
        public string hased_pwd { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<tbl_duty> tbl_duty { get; set; }
        public virtual tbl_group tbl_group { get; set; }
        public virtual ICollection<tbl_menu_selection> tbl_menu_selection { get; set; }
    }
}
