//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_group
    {
        public tbl_group()
        {
            this.tbl_people = new HashSet<tbl_people>();
        }
    
        public long id { get; set; }
        public string group_name { get; set; }
        public Nullable<bool> is_admin { get; set; }
    
        public virtual ICollection<tbl_people> tbl_people { get; set; }
    }
}
