//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_meal
    {
        public tbl_meal()
        {
            this.tbl_menu = new HashSet<tbl_menu>();
        }
    
        public long id { get; set; }
        public string meal_name { get; set; }
    
        public virtual ICollection<tbl_menu> tbl_menu { get; set; }
    }
}
