//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_menu_selection
    {
        public long id { get; set; }
        public long id_menu { get; set; }
        public long id_people { get; set; }
        public Nullable<byte> qty { get; set; }
    
        public virtual tbl_menu tbl_menu { get; set; }
        public virtual tbl_people tbl_people { get; set; }
    }
}
